library: ~/music/Library.blb
directory: ~/music
import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
plugins: embedart fetchart replaygain mbsync
threaded: yes

paths:
    default: $albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    comp: Compilations/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title

replaygain:
    backend: gstreamer
